<x-layout>
    @session('success')
    <p class="alert alert-success"> {{ session('success') }}</p> 
    @endsession    
       <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <span>Financial Overview</span>
                <!-- <select class="form-select form-select-sm" id="fetchval" style="width: auto;">
                    <option value="All">All Bills</option>
                    <option value="pending">Pending</option>
                    <option value="paid">Paid</option>
                </select> -->
            </div>
            <div class="table-responsive">
                <table class="table table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>Unit</th>
                            <th>Bill Type</th>
                            <th>Amount</th>
                            <th>Month</th>
                            <th>Generated By</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody id="billdata">
                        @foreach($bills as $bill)
                        <tr>
                            <td>{{ $bill->home->house_no }}</td>
                            <td>{{ $bill->bill_type }}</td>
                            <td class="fw-bold text-dark">{{ $bill->amount}}</td>
                            <td>{{ $bill->month }}</td>
                            <td>{{ $bill->generator->name }} ({{ $bill->generator->role }})</td>
                            <td><span class="status-badge bg-success text-white">{{ $bill->status }}</span></td>
                            <td><a href="{{ route('pay.bill', $bill->id)}}" class="btn btn-danger" title="Revoke Bill">
                                    <i class="fas fa-trash-alt"></i> Pay
                                </a>
                            </td>    
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


</x-layout>